Repository AlxFrst/daily-sneakers, pull requests merged in 2022-06, with the labels that each got.

#17 show page build
  app/assets/images/T1.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/pages/_show.scss
  app/views/shared/_navbar.html.erb
  app/views/sneakers/show.html.erb
Labels: Front-End

#19 Une seed comme j'en ai rarement vu...
  db/seeds.rb
Labels: Back-End, Fix, DEV

#37 fix search in the navbar
  app/controllers/sneakers_controller.rb
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: Back-End, Front-End, Fix

#46 Back end correction
  app/controllers/collections_controller.rb
  app/controllers/wishlists_controller.rb
  app/models/collection.rb
  app/views/dashboards/collection.html.erb
  app/views/dashboards/wishlist.html.erb
  app/views/sneakers/show.html.erb
  config/routes.rb
  db/seeds.rb
  test/controllers/collections_controller_test.rb
Labels: Back-End, Fix

#53 awesome show page
  app/javascript/channels/dropdown.js
  app/javascript/channels/graph.js
  app/javascript/controllers/market_controller.js
  app/javascript/packs/application.js
  app/views/shared/_sizer.html.erb
  app/views/sneakers/show.html.erb
  db/seeds.rb
Labels: Back-End, Front-End, Fix

#66 Meta
  app/assets/images/cover.png
  app/assets/images/favicon.ico
  app/controllers/application_controller.rb
  app/controllers/dashboards_controller.rb
  app/helpers/meta_tags_helper.rb
  app/views/dashboards/collection.html.erb
  app/views/dashboards/wishlist.html.erb
  app/views/layouts/application.html.erb
  config/initializers/default_meta.rb
  config/meta.yml
  public/500.html
Labels: Back-End, Features
